{% set name = "ads2inspire" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60a44e917e50af5476fb55ee7589a9f74539359e6e9a0ff307473bfa6bdc3be7

build:
  noarch: python
  number: 0
  entry_points:
    - ads2inspire = ads2inspire.cli:ads2inspire
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.6
    - bibtexparser
    - click >=6.0

test:
  imports:
    - ads2inspire

about:
  home: https://github.com/duetosymmetry/ads2inspire
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Replace ADS citations with the appropriate INSPIRE ones in latex and bibtex

  description: |
    ads2inspire is a command-line utility (and package) for replacing
    ADS citations with the appropriate INSPIRE ones in latex and bibtex.
    It is pure Python code with minimal dependencies.
  doc_url: https://github.com/duetosymmetry/ads2inspire
  dev_url: https://github.com/duetosymmetry/ads2inspire

extra:
  recipe-maintainers:
    - duetosymmetry
