{% set name = "ads2inspire" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ebfe4b692ff57d32f3756bf9350416bfab9e56f707e098877d895e752c47cfb

build:
  noarch: python
  number: 1
  entry_points:
    - ads2inspire = ads2inspire.cli:ads2inspire
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >={{ python_min }}
    - bibtexparser
    - click >=6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ads2inspire

about:
  home: https://github.com/duetosymmetry/ads2inspire
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Replace ADS citations with the appropriate INSPIRE ones in latex and bibtex

  description: |
    ads2inspire is a command-line utility (and package) for replacing
    ADS citations with the appropriate INSPIRE ones in latex and bibtex.
    It is pure Python code with minimal dependencies.
  doc_url: https://github.com/duetosymmetry/ads2inspire
  dev_url: https://github.com/duetosymmetry/ads2inspire

extra:
  recipe-maintainers:
    - duetosymmetry
